sudo: false

language: java
jdk:
  - oraclejdk8
  - openjdk8

script: mvn clean verify -B -P coverage
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn clean deploy -B

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master
    - develop
